# Generated by Django 4.2.4 on 2023-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.TextField(max_length=100, verbose_name='фамилия'),
        ),
    ]
